services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      # So you don't have to use root, but you can if you like
      POSTGRES_USER: '${POSTGRES_USER}'
      # You can use whatever password you like
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    volumes:
      - type: volume
        source: pg_api_call
        target: /var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - '5432:5432' # expose ports - HOST:CONTAINER
    restart: unless-stopped
volumes:
  pg_api_call:
